### ISSUE TITLE
Error: Unable to load crawler from ./nightcrawler.js

### ISSUE THREAD

**Issue by AhmadMari** [LastCallMedia/Night-Crawler#13]
throw new Error(`Unable to load crawler from ${_yargs2.default.argv.config}`);
  ^

Error: Unable to load crawler from ./nightcrawler.js
    at Object.<anonymous> (/root/ttt/Night-Crawler/dist/cli/index.js:18:9)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/root/ttt/Night-Crawler/bin/nightcrawler:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

Steps to reproduce:
Follow the README.md file exactly https://github.com/LastCallMedia/Night-Crawler

**Comment by rbayliss** [comment]
Hello!  Thanks for reporting this.  I wasn't able to replicate this issue following the instructions from the README, although I did note that following the instructions got me the in-development 2.x branch, which causes some other issues.  But I think the issue you're running into might be that you cloned this project down rather than using `npm install` or `yarn add`.

I suggest the following:
1. Run `yarn add lastcall-nightcrawler@1.0` or `npm install lastcall-nightcrawler@^1.0` (depending on whether you're using npm or yarn).
2. Follow the instructions from the README to create your `nightcrawler.js` file. 
3. Run `node_modules/.bin/nightcrawler crawl`

Hopefully that will get you started.
